### ISSUE TITLE
Bug: change change listening port

### ISSUE THREAD

**Issue by goodideal** [blacklabelops/crowd#10]
Refer to [Changing the Port that Crowd uses](https://confluence.atlassian.com/crowd/changing-the-port-that-crowd-uses-38797397.html), the `crowd.tomcat.connector.port` property in build.properties has to be changed to `NEW PORT`. But it wasn't included in the script.

**Comment by blacklabelops** [comment]
I do not understand. Does the default port not work properly?

**Comment by blacklabelops** [comment]
No answer, no solution.
