### ISSUE TITLE
how can I VOLUME /var/atlassian/crowd

### ISSUE THREAD

**Issue by huayanYu** [blacklabelops/crowd#18]
Hello
### I see u dockerFile like this
```shell
addgroup -g $CONTAINER_GID $CONTAINER_GROUP &&  \
    adduser -u $CONTAINER_UID \
            -G $CONTAINER_GROUP \
            -h /home/$CONTAINER_USER \
            -s /bin/bash \
            -S $CONTAINER_USER &&  \
```
### I run crowd like this
```shell
groupadd crowd && useradd crowd -g crowd && mkdir -p /opt/docker/crowd && chown -R crowd:crowd /opt/docker/crowd

docker run \
--name crowd \
-p 80:8095 \
-v /etc/localtime:/etc/localtime \
-v /opt/docker/crowd:/var/atlassian/crowd \
--restart=always \
-d blacklabelops/crowd
```
### I get the following errors
```shell
2018-04-10 03:39:13,315 localhost-startStop-1 INFO [atlassian.crowd.service.HomeDirectoryServiceImpl] Shared home directory doesn't exist, trying to create an empty one in /var/atlassian/crowd/shared
2018-04-10 03:39:13,317 localhost-startStop-1 ERROR [crowd.console.listener.BootstrapLoaderListener] An error was encountered while starting Crowd (see below): 
Could not create shared home directory at /var/atlassian/crowd/shared
java.lang.RuntimeException: Could not create shared home directory at /var/atlassian/crowd/shared
```

## how to resove this problem?

**Comment by blacklabelops** [comment]
Do not do this: `groupadd crowd && useradd crowd -g crowd && mkdir -p /opt/docker/crowd && chown -R crowd:crowd /opt/docker/crowd`

Each time you add a user to your host machine you create a new user with new userid and groupid. Chances are high this will never match CONTAINER_UID (User id) and CONTAINER_GROUP (groupid). Not the name but userid and groupid must match.

And give crowd a Docker volume: `docker volume create crowd`

Run with volume: docker run `-v crowd:/var/atlassian/crowd`

Do not do this: `-v /etc/localtime:/etc/localtime \`

Use timezone environment variable, Example:`'TZ=Europe/Berlin'`
