### ISSUE TITLE
3.3.5 Update

### ISSUE THREAD

**Issue by iwalmsley** [blacklabelops/crowd#29]
Hi there, 

I noticed that this repository has been updated to publish the 3.3.5 version, will this be pushed to Dockerhub? Looks like 3.3.0 is the latest version that has been published - https://hub.docker.com/r/teamatldocker/crowd/tags

Thanks alot

**Comment by blacklabelops** [comment]
Someone forgot to adjust the build system. 

In order to get a 3.3.5 tag inside dockerhub you need to adjust and maintain `buildscripts/release.sh`.

There is still a 3.3.0 in there.

Means, version 3.3.5 is now 3.3.0 in Dockerhub and there is no 3.3.0. 3.3.0 has been overwritten.

**Comment by iwalmsley** [comment]
Thanks for the quick response!

I've tried pulling both teamatldocker/crowd:3.3.0 & teamatldocker/crowd:latest - both of them report as being 3.3.0 in the Crowd UI/logs on boot.

**Comment by blacklabelops** [comment]
Your right `buildscripts/release.sh` is also responsible for building the images. So there is no 3.3.5 currently.

**Comment by blacklabelops** [comment]
Fixed, 3.3.5 is now available.
