### ISSUE TITLE
Having issues loading... still investigating. 

### ISSUE THREAD

**Issue by pironic** [blacklabelops/crowd#5]
just as the title suggests "mysql support please"... including the drivers for mysql as an option would help me out loads. been trying to get this working for a couple weeks on and off without much luck. an out of the box solution would go miles.

**Comment by pironic** [comment]
upon further inspection into the root i see that you indeed have the support in the Dockerfile already declared... i'm going to keep investigating my causes. one thing i've done differently than what you've suggested is set up an external volume for /var/atlassian/crowd to a local drive. i want to be able to rebuild my docker images without having to install again every time... this might be the cause, but more to come...

**Comment by pironic** [comment]
I think i'm just going to wait for https://github.com/mergermarket/crowd/commit/7d21626cb56b9596dd75172a0888bb9b3263d2ce to be completed. Enough troubleshooting for one day.

**Comment by blacklabelops** [comment]
Can you please tell me what mysql version and image you are using?

**Comment by pironic** [comment]
here is my docker run command:

```
sudo docker run \
--name=crowd \
-v /config/crowd/home:/var/atlassian/crowd \
-v /mnt/ostium/ssl:/ssl \
-e CROWD_URL=http://localhost:8095/ \
-e CROWDDB_URL=mysql://crowduser:jellybean@10.1.1.20/crowd \
-e CFOWDIDDB_URL=mysql://crowduser:jellybean@10.1.1.20/crowdid \
-e CROWDID_CONTEXT=openid \
-e CROWD_CONTEXT=ROOT \
-e SPLASH_CONTEXT= \
-e DEMO_CONTEXT=demo \
-e OPENID_CLIENT_CONTEXT=profile \
-e CROWD_PROXY_NAME=https://crowd.domain.com/ \
-e CROWD_PROXY_PORT=443 \
-e CROWD_PROXY_SCHEME=https \
-p 8095:8095 \
blacklabelops/crowd
```

the MySQL is `Server version: 5.5.37-0ubuntu0.12.10.1 (Ubuntu)`


when starting up i always see this: 

```
INFO: Deploying configuration descriptor /opt/crowd/apache-tomcat/conf/Catalina/localhost/openid.xml
Apr 23, 2017 8:17:32 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2017-04-23 20:17:33,596 localhost-startStop-1 WARN [springframework.context.support.PropertySourcesPlaceholderConfigurer] Could not load properties from URL [
file:${crowd.openid.home}/jdbc.properties]: ${crowd.openid.home}/jdbc.properties (No such file or directory)
2017-04-23 20:17:33,597 localhost-startStop-1 WARN [springframework.context.support.PropertySourcesPlaceholderConfigurer] Could not load properties from URL [
file:${crowd.openid.home}/crowd.properties]: ${crowd.openid.home}/crowd.properties (No such file or directory)
2017-04-23 20:17:33,598 localhost-startStop-1 WARN [springframework.context.support.PropertySourcesPlaceholderConfigurer] Could not load properties from URL [
file:${crowd.openid.properties}]: ${crowd.openid.properties} (No such file or directory)
2017-04-23 20:17:35,228 localhost-startStop-1 INFO [com.atlassian.crowd.startup] Starting the Crowd OpenID server, version: 2.11.1 (Build:#726 - 2017-03-10)

*********************************************************************************************
*
*  You can now use the Crowd OpenID server by visiting http://localhost:8095/openid
*
*********************************************************************************************
```

and /config/crowd/home is empty. it can make the directory fine but it doesn't fill it with anything. even when the directory is premade 777 it still doesn't fill it.

**Comment by blacklabelops** [comment]
There is a spelling error "CFOWDIDDB_URL" must be "CROWDIDDB_URL". 

Also the ip adress "10.1.1.20" looks suspicious. 

- Is this a Docker container? Won't work because ip adresses inside Docker change. You must use a network name.
- Is this an MySQL demon on the host machine? Won't work, because by default there is no network route from inside a Docker network to the host machine.

**Comment by blacklabelops** [comment]
Upon further inspection I can tell you that CROWDDB_URL and CROWDIDDB_URL do not work in the latest crowd release. You have to go through the crowd setup wizard in order to setup crowd and crowdid. Afterwards restart the container and access the crowdid context with your crowd admin account.

**Comment by pironic** [comment]
Thanks for taking a look: 

The ip address `10.1.1.20` is the mysql database. it is not a docker instance. full fledged database server separate from the docker server... should be accessible by the docker image though. I have noticed that i've been forced to go through the wizard but that still doesn't explain the other issues of nothing in /var/atlassian/crowd inside the container :( 

Further testing inbound...

**Comment by pironic** [comment]
i may have found the cause... but not the remedy yet, just a workaround:

the volume is added to the container with the root user and created on the host system as root... but the scripts inside the container run as user crowd. It's a simple user permission issue... 

it looks like the uid of the user is 1000 so creating the folders on the docker host before you create the container is necessary if you want to mount a persistent volume.

**To correct this, i think it might be best to add a line in the Dockerfile that validates the permissions of the CROWD_HOME and CROWD_INSTALL variables. make sure they are owned and accessible by uid:1000 (crowd).**

**Comment by blacklabelops** [comment]
This issue happens because you have mounted host directories with `-v /config/crowd/home:/var/atlassian/crowd -v /mnt/ostium/ssl:/ssl ` and would not happen if you use docker volumes.

Another fix would be if your system has a user with the user id 1000 and group id 1000. Make sure that the mounted directory has write permissions for the user and the directory `/config/crowd/home` must be empty. Otherwise the mount behavior of Docker will not copy the images files to the folder.

No change inside the Dockerfile will fix this issue. I could only add a check to the entrypoint that will check this issue and notify before shutting down. Not sure if that would help you.
